# Generated by Django 3.1.4 on 2022-01-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20211230_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
