# Generated by Django 3.1.4 on 2022-01-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20220112_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date_created',
            new_name='time_created',
        ),
    ]
